version = 0.1
[default.deploy.parameters]
stack_name = "auto-tag"
resolve_s3 = true
s3_prefix = "auto-tag"
region = "eu-west-3"
profile = "okta"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Region=\"eu-west-3\" ACCOUNTID=\"808047697977\" DefaultTagKey=\"CostCenter\" DefaultTagValue=\"Qubole-Prod\" RDSCommercialTagValue=\"CostCenter\" RDSNonCommercialTagValue=\"Qubole-Prod\""
image_repositories = []
