version = 0.1
[default.deploy.parameters]
stack_name = "auto-tag"
resolve_s3 = true
s3_prefix = "auto-tag"
region = "sa-east-1"
profile = "okta"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Region=\"sa-east-1\" ACCOUNTID=\"330183209093\" DefaultTagKey=\"CostCenter\" DefaultTagValue=\"Qubole-Dev\" RDSCommercialTagValue=\"CostCenter\" RDSNonCommercialTagValue=\"Qubole-Dev\""
image_repositories = []
