version = 0.1
[default.deploy.parameters]
stack_name = "auto-tag"
resolve_s3 = true
s3_prefix = "auto-tag"
region = "us-east-2"
profile = "okta"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Region=\"us-east-2\" ACCOUNTID=\"176510560049\" DefaultTagKey=\"CostCenter\" DefaultTagValue=\"Qubole-Prod\" RDSCommercialTagValue=\"CostCenter\" RDSNonCommercialTagValue=\"Qubole-Prod\""
image_repositories = []
