version = 0.1
[default.deploy.parameters]
stack_name = "auto-tag"
resolve_s3 = true
s3_prefix = "auto-tag"
region = "ap-northeast-2"
profile = "okta"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Region=\"ap-northeast-2\" ACCOUNTID=\"122763066428\" DefaultTagKey=\"CostCenter\" DefaultTagValue=\"Qubole-QA\" RDSCommercialTagValue=\"CostCenter\" RDSNonCommercialTagValue=\"Qubole-QA\""
image_repositories = []
